language: ruby

rvm:
  - 1.9.3
  - 2.0.0
  - 2.1.0
  - 2.2.2
  - 2.3.0

env:
  - 'RAILS_VERSION=4.1.0'
  - 'RAILS_VERSION=4.2.0'
  - 'RAILS_VERSION=5.x'

bundler_args: --without development

before_install: gem install bundler -v 1.10.5

matrix:
  exclude:
    # Rails 5 Only Support Ruby >= 2.2.2
    - rvm: 1.9.3
      env: 'RAILS_VERSION=5.x'
    - rvm: 2.0.0
      env: 'RAILS_VERSION=5.x'
    - rvm: 2.1.0
      env: 'RAILS_VERSION=5.x'
